//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Departments
    {
        public int Id { get; set; }
        public string HOD { get; set; }
        public Nullable<int> RefHRID { get; set; }
        public string Department { get; set; }
    
        public virtual HR_SignUp HR_SignUp { get; set; }
    }
}
