//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmpBankInformations
    {
        public int Id { get; set; }
        public int Employee_ID { get; set; }
        public string Bankname { get; set; }
        public string Bankaccno { get; set; }
        public string IFSCCode { get; set; }
        public string Panno { get; set; }
    
        public virtual t_Employees t_Employees { get; set; }
    }
}
