//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PersonalInformations
    {
        public int Id { get; set; }
        public int Employee_ID { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> Passport_Exp_Date { get; set; }
        public string Tel { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Maritalstatus { get; set; }
        public string EmrName1 { get; set; }
        public string EmrRelation1 { get; set; }
        public string EmrPhone11 { get; set; }
        public string EmrPhone12 { get; set; }
        public string EmrName2 { get; set; }
        public string EmrRelation2 { get; set; }
        public string EmrPhone21 { get; set; }
        public string EmrPhone22 { get; set; }
        public string Bankname { get; set; }
        public string Bankaccno { get; set; }
        public string IFSCCode { get; set; }
        public string Panno { get; set; }
    
        public virtual t_Employees t_Employees { get; set; }
    }
}
